--1. Add column state varchar(20).  

SELECT *FROM DEPOSIT;
ALTER TABLE DEPOSIT ADD STATE VARCHAR(20);

--2. Add two more columns city varchar(20) and pincode int. 

SELECT *FROM DEPOSIT
ALTER TABLE DEPOSIT ADD CITY VARCHAR(20) , PINCODE VARCHAR(20);

--3. Change the size of cname column from varchar(50) to varchar(35). 

SELECT *FROM DEPOSIT
ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)

--4. Change the data type of amount from decimal to int.  

SELECT *FROM DEPOSIT
ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT;

--5. Delete column city from the DEPOSIT table.  

SELECT *FROM DEPOSIT
ALTER TABLE DEPOSIT DROP COLUMN CITY;

--6. Rename column actno to ano.  

SELECT *FROM DEPOSIT
EXEC SP_RENAME 'DEPOSIT.ACTNO','ANO'

EXEC SP_RENAME 'BANK_DEPOSIT.ANO','ANO'

--7. Rename column bname to branch_name.

SELECT *FROM DEPOSIT
EXEC SP_RENAME 'DEPOSIT.BNAME','BRANCH_NAME'

--8. Rename table DEPOSIT to DEPOSIT_DETAIL.  

SELECT *FROM DEPOSIT_DETAIL
EXEC SP_RENAME DEPOSIT,DEPOSIT_DETAIL

--9. Add column ifsc_code varchar(15).  

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL
ADD IFSC_CODE VARCHAR(15)

--10. Change the size of bname column from varchar(50) to varchar(30). 

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL ALTER COLUMN BRANCH_NAME VARCHAR(30)

--11. Rename column adate to aopendate.  

SELECT *FROM DEPOSIT_DETAIL
EXEC SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

--12. Delete column aopendate from DEPOSIT_DETAIL table.  

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL  DROP COLUMN AOPENDATE

--13. Rename column cname to customer_name.  

SELECT *FROM DEPOSIT_DETAIL
EXEC SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMER_NAME'

--14. Add column country varchar(20).  

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL ADD COUNTRY VARCHAR(20)

--15. Add column account_type varchar(15). 

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL ADD ACCOUNT_TYPE VARCHAR(15)

--16. Change data type of pincode from int to bigint. 

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL ALTER COLUMN PINCODE BIGINT

--17. Delete column account_type. 

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL  DROP COLUMN ACCOUNT_TYPE

--18. Rename column amount to balance. 

SELECT *FROM DEPOSIT_DETAIL
EXEC SP_RENAME 'DEPOSIT_DETAIL.AMOUNT','BALANCE'

--19. Add column status varchar(10). 

SELECT *FROM DEPOSIT_DETAIL
ALTER TABLE DEPOSIT_DETAIL ADD STATUS VARCHAR(10)

--20. Change table name deposit_detail to bank_deposit. 

EXEC SP_RENAME DEPOSIT_DETAIL,BANK_DEPOSIT
SELECT *FROM BANK_DEPOSIT

--1. Delete all the records having amount less than or equal to 3000.  

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT WHERE BALANCE <=3000

--2. Delete all the accounts of ‘BEDI’ branch customer. 

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT WHERE BRANCH_NAME = 'BEDI'

--3. Delete all the accounts having account number greater than 102 and less than 109.  

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT WHERE DEPOSIT.ANO >102 AND DEPOSIT.ANO <109

--4. Delete all the accounts whose branch is ‘BEDI’ or ‘MADHAPAR’.

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT WHERE BRANCH_NAME ='BEDI' OR BRANCH_NAME='MADHAPAR'

--5. Delete all the accounts details where amount is 8000 and account open after 1-1-2025; 

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT WHERE BALANCE=8000 AND AOPENDATE > 1-1-2025

--6. Delete all the accounts whose account branch is NULL.  

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT WHERE BRANCH_NAME IS NULL

--7. Delete all the accounts details where amount is 7000 and name is CHARMI and branch is SHITAL PARK.

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT WHERE BALANCE=7000 AND (CUSTOMER_NAME='CHARMI' AND BRANCH_NAME='SHITAL PARK') 

--8. Delete all the remaining records using DELETE command. 

SELECT *FROM BANK_DEPOSIT
DELETE FROM BANK_DEPOSIT

--9. Delete all the records of DEPOSIT table. (Use TRUNCATE)  

TRUNCATE TABLE BANK_DEPOSIT

--10. Remove DEPOSIT table. (Use DROP) 
DROP TABLE BANK_DEPOSIT

--11. Delete all the students whose stdid is greater than 105. 

SELECT *FROM STUDENT
DELETE FROM STUDENT WHERE STDID > 105

--12. Delete the records whose branch is NULL and sname is not NULL.  

SELECT *FROM STUDENT
DELETE FROM STUDENT WHERE BRANCH IS NULL AND SNAME IS NOT NULL

--13. Delete the records whose SPI is less than 9 and city is RAJKOT.  

SELECT *FROM STUDENT
DELETE FROM STUDENT WHERE SPI < 9 AND CITY='SURAT'

--14. Delete the records whose branch name is not empty.  

SELECT *FROM STUDENT
DELETE FROM STUDENT WHERE BRANCH IS NOT NULL

--15. Delete all the records of STUDENT table. (Use TRUNCATE) 

TRUNCATE TABLE STUDENT
